"""fix part number mistake

Revision ID: 21be73e7f51e
Revises: 33dddddec5f3
Create Date: 2024-04-16 21:25:31.030172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21be73e7f51e'
down_revision = '33dddddec5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('part_number')

    # ### end Alembic commands ###
