"""Make org created_at immutable

Revision ID: 2fda9c1b81c1
Revises: 0c24a203d7a5
Create Date: 2024-04-17 15:50:56.984090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fda9c1b81c1'
down_revision = '0c24a203d7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
