"""Replace org.created_by with org.user_id

Revision ID: 3ea3452ac0f5
Revises: 409f4f85a8d8
Create Date: 2024-04-17 21:12:20.655603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea3452ac0f5'
down_revision = '409f4f85a8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_organizations_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('creator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_organizations_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
