"""add creator cols

Revision ID: 409f4f85a8d8
Revises: 1b693d513eeb
Create Date: 2024-04-17 16:49:50.495125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409f4f85a8d8'
down_revision = '1b693d513eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('created')
        batch_op.drop_column('creator')

    # ### end Alembic commands ###
