"""Make emails unique

Revision ID: 85910bd1fe5c
Revises: 9095ba01275a
Create Date: 2024-04-06 15:36:16.659931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85910bd1fe5c'
down_revision = '9095ba01275a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    # ### end Alembic commands ###
