"""Add item constraints

Revision ID: 9d470ef2c2bc
Revises: 98d690973329
Create Date: 2024-04-21 08:07:59.743445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d470ef2c2bc'
down_revision = '98d690973329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_items_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_items_part_number'), ['part_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_items_part_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_items_name'), type_='unique')

    # ### end Alembic commands ###
